# Example parameter file for SV calling pipeline
# Usage: nextflow run main.nf -params-file params.yaml

# Pipeline run name
run_name: 'benchmarking_run'

# Output directory
outdir: 'results'

# Reference genome (REQUIRED)
fasta: '/path/to/reference/genome.fasta'

# Input BAM files (provide at least one)
illumina_wes_bam: null
illumina_wgs_bam: null
pacbio_bam: null
ont_bam: null

# Benchmarking files (optional - set skip_benchmarking: true if not using)
benchmark_vcf: null
skip_benchmarking: false
high_confidence_targets: null
gene_panel_targets: null
wes_utr_targets: null

# Optional: Tandem repeats BED file (recommended for Sniffles)
tandem_repeats: null

# Truvari benchmarking parameters
truvari_refdist: 500
truvari_pctsize: 0.7
truvari_pctovl: 0
truvari_pctseq: 0

# WES-specific Truvari parameters (if different from above)
truvari_wes_refdist: 500
truvari_wes_pctsize: 0.7
truvari_wes_pctovl: 0
truvari_wes_pctseq: 0

# Resource limits
max_cpus: 24
max_memory: '128.GB'
max_time: '48.h'

# Optional features
simulate_targets: false
gather_statistics: false
